Improved request call

diff --git a/.github/workflows/update-tokens.yml b/.github/workflows/update-tokens.yml
--- a/.github/workflows/update-tokens.yml
+++ b/.github/workflows/update-tokens.yml
@@ -17,10 +17,15 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v3
 
+      - name: Define Repository List File
+        run: echo "REPOS=repos.txt" >> $GITHUB_ENV
+
       - name: Verify Repository List File
+        env:
+          REPOS: ${{ env.REPOS }}
         run: |
-          if [ ! -f repos.txt ]; then
-            echo "Error: repos.txt not found!"
+          if [ ! -f $REPOS ]; then
+            echo "Error: $REPOS not found!"
             exit 1
           fi
 
@@ -45,5 +50,7 @@ jobs:
         run: |
           while IFS= read -r REPO; do
             echo "Updating secret for $REPO..."
-            gh secret set ACCESS_TOKEN -b "$RECEIVED_TOKEN" --repo "$REPO" || echo "Failed to update $REPO"
-          done < repos.txt
+            gh secret set ACCESS_TOKEN -b "$RECEIVED_TOKEN" --repo "$REPO" || { 
+              echo "Failed to update $REPO"; exit 1; 
+            }
+          done < "$REPOS"
